version: "3.7"

services:

  postgres_sandbox:
    container_name: postgres_sandbox
    platform: linux/amd64
    image: postgres:13
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pg-admin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./.env
    depends_on:
      postgres_sandbox:
        condition: service_healthy
    ports:
      - "5050:5050"

  python:
    container_name: python
    build: .
    image: python_for_pg
    env_file:
      - ./.env

volumes:
  pgdata:
